version: "3.3"

services:
  app:
    build:
      context: .
    volumes:
      - ./backend:/backend
    env_file:
      - .env

  arq:
    build:
      dockerfile: Dockerfile.arq
      context: .
    volumes:
      - ./backend:/backend
    env_file:
      - .env