version: "3.3"

services:
  app:
    depends_on:
      - db
      - redis
    ports:
      - "80:8000"

  db:
    image: postgres:12
    volumes:
      - ./data/postgres:/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_USER=$DB_USER
      - POSTGRES_DB=$DB_NAME

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/var/lib/redis
    command: redis-server --requirepass ${REDIS_PASSWORD} --protected-mode yes