"""auto

Revision ID: 83a1ab42ab3d
Revises: f23ea41bea22
Create Date: 2022-03-20 14:21:46.438333

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '83a1ab42ab3d'
down_revision = 'f23ea41bea22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_user', sa.Column('is_email_verified', sa.Boolean(), nullable=False, server_default="FALSE"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('app_user', 'is_email_verified')
    # ### end Alembic commands ###
